version: "3.2"

services:
  integration_tests:
    restart: always
    networks:
      - vegadns_net
    image: vegadns/cli:${CLI_TAG}
    # Helpful for debugging
    # volumes:
    #   - ${PWD}/../VegaDNS-CLI:/opt/vegadns-cli
    environment:
      HOST: ${HOST}
      NAMESERVER: tinydns
